--- #YAML:1.0
name: Bot-BasicBot-Pluggable-Module-Tools
version: 0.8
author: Simon Wistow <simon@thegestalt.org>
abstract: |-
  a miscellany of useful plugins for Bot::BasicBot::Pluggable
license: perl
requires:
  Bot::BasicBot::Pluggable: 0.1
  Finance::Currency::Convert::XE: 0
  Finance::Quote: 0
  Locale::Language: 0
  Math::Expression: 0
  Math::Units: 0
  Test::More: 0
  WWW::MakeAShorterLink: 0
provides: {}
generated_by: Module::Build version 0.25
